### ISSUE TITLE
Rust tools not configured properly

### ISSUE THREAD

**Issue by amaanq** [appelgriebsch/Nv#1]
I have a pretty similar rust config to yours for rust (thank you for the inspiration btw!), and after several days did I only realize a potential issue..the cargo command was not clippy and it's due to the rust-tools setup call. rust-tools' lsp options are in the "server" key of the opts table, but yours is just passing the table as is.

The change should be as follows:
```
require("rust-tools").setup(rust_tools_opts)
-- to
require("rust-tools").setup({ server = rust_tools_opts })
```

Although if you already have rust-tools running clippy, that'd be interesting as without the server key set it would not run clippy for me.

**Comment by appelgriebsch** [comment]
Looks like the `rust-analyser` options have changed a bit recently, so most of the stuff I had in the config didn't work any longer. Updated it according to latest docs and works fine for me now.
