### ISSUE TITLE
[Rust] Incorrect LSP configuration

### ISSUE THREAD

**Issue by utkarshgupta137** [appelgriebsch/Nv#5]
I had copied the Rust code from this repo & was debugging some issue when I realised that the LSP isn't being configured correctly.

This is the problematic part of the code (https://github.com/appelgriebsch/Nv/blob/main/lua/plugins/extras/lang/rust.lua#L62-L91):
```lua
          local rust_tools_opts = vim.tbl_deep_extend("force", opts, {
            tools = {
              hover_actions = {
                auto_focus = false,
                border = "none",
              },
              inlay_hints = {
                auto = false,
                show_parameter_hints = true,
              },
            },
            server = {
              settings = {
                ["rust-analyzer"] = {
                  cargo = {
                    features = "all",
                  },
                  -- Add clippy lints for Rust.
                  checkOnSave = true,
                  check = {
                    command = "clippy",
                    features = "all",
                  },
                  procMacro = {
                    enable = true,
                  },
                }
              }
            }
          })
```

This is how it should be:
```lua
          local rust_tools_opts = {
            tools = {
              hover_actions = {
                auto_focus = false,
                border = "none",
              },
              inlay_hints = {
                auto = false,
                show_parameter_hints = true,
              },
            },
            server = vim.tbl_deep_extend("force", opts, {
              settings = {
                ["rust-analyzer"] = {
                  cargo = {
                    features = "all",
                  },
                  -- Add clippy lints for Rust.
                  checkOnSave = true,
                  check = {
                    command = "clippy",
                    features = "all",
                  },
                  procMacro = {
                    enable = true,
                  },
                }
              }
            })
          }
```

**Comment by appelgriebsch** [comment]
How is the LSP not configured correctly for you? I have no issues with any Rust project....?

**Comment by utkarshgupta137** [comment]
Yeah, the LSP works fine for the most part. I was debugging some unrelated formatting issue & found that the client-side capabilities weren't being passed to rust-analyzer correctly.
rust-tools' [docs](https://github.com/simrat39/rust-tools.nvim/#configuration) state that all the parameters that need to be passed to rust-analyzer need to be inside the `server` section.

**Comment by appelgriebsch** [comment]
Yeah, just got it. Will prepare a fix soon. Thanks for your feedback!

**Comment by utkarshgupta137** [comment]
Here is my config: https://github.com/utkarshgupta137/nvim-lazy/blob/main/lua/lvim/lsp/rust-tools.lua (mostly stolen from you).

**Comment by utkarshgupta137** [comment]
BTW, are you interested in reviving https://github.com/LazyVim/LazyVim/pull/24? I am coming from AstroNvim & the [astrocommunity](https://github.com/AstroNvim/astrocommunity) configs made it really easy to quickly add new features to the editor.
