### ISSUE TITLE
NV_THEME Variable Usage (Not an issue)

### ISSUE THREAD

**Issue by genortech** [appelgriebsch/Nv#6]
Hi, Amazing setup and I have been following and trying to use your setup to understand Neovim and how it works. I have been using it as a guide to setup my own. 

I do have a question as new user to Neovim, I am a bit stumped on how to use the NV_THEME Variable used for the colorscheme, where to I set this variable? Would you be kind as to provide some guidance on how this done?

Thank you for your time.
Keep up the amazing work.

**Comment by appelgriebsch** [comment]
Hey, thanks for your feedback. Depending on the shell you are using you have to add the environment variable to the respective shell profile - e.g. on Bash in https://www.howtogeek.com/668503/how-to-set-environment-variables-in-bash-on-linux/

**Comment by genortech** [comment]
Awesome. Thanks for the help. Again amazing work. I havent gotten to get the colourscheme switching properly but its a matter of time.
