### ISSUE TITLE
Issues debugging Java Tests

### ISSUE THREAD

**Issue by arnaupv** [appelgriebsch/Nv#7]
Hi! Amazing setup, thanks for sharing!

I've been recently experiencing issues with the last version of the [java-debug-adapter (0.52.0)](https://github.com/microsoft/vscode-java-debug/tree/0.52.0).
(defined [here](https://github.com/appelgriebsch/Nv/blob/main/lua/plugins/extras/lang/java.lua#L28) in your config)

In order to be able to continue debugging the Java Test, I've had to downgrade from 0.52.0 to 0.51.0
This caused me some issues with mason-nvim-dap.nvim, as you can see in my [issue](https://github.com/jay-babu/mason-nvim-dap.nvim/issues/100). I'm propose a hotfix in the same issue. 

It would be great to know if you are experiencing the same problem  with the version 0.52.0

Thanks!

**Comment by appelgriebsch** [comment]
Hmmm not sure what is meant, just removed all my local neovim folders, and went through the initial setup procedure again. Everything works as expected and all the LSP and DAP handlers were installed afterwards....
