### ISSUE TITLE
rust type prompts are not displayed

### ISSUE THREAD

**Issue by ClzSkywalker** [appelgriebsch/Nv#8]
Hi author, I saw the following image in your introduction image, rust has a type hints, but I used your configuration without a type hints.
I have used neovim9 and 10 in ubuntu without rust type hints

![Snipaste_2023-09-13_23-40-27](https://github.com/appelgriebsch/Nv/assets/44250611/3bf0b080-f84c-4db9-b3e7-87cc0c70db15)

The diagram below is the result of my own configuration
![Snipaste_2023-09-13_23-43-46](https://github.com/appelgriebsch/Nv/assets/44250611/a93fbabf-cda9-45b4-8ccb-7368a762f226)

**Comment by appelgriebsch** [comment]
InlayHints are still a neovim-nightly only feature and as such not guaranteed to work on every installation….
